// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Hozirgi active window — bir martalik so'rov
Future<WindowInfo?> currentWindow() =>
    RustLib.instance.api.crateApiWindowMonitorCurrentWindow();

/// Active window'ni uzluksiz kuzatish.
Stream<WindowInfo> watchActiveWindow({required int pollMs}) =>
    RustLib.instance.api.crateApiWindowMonitorWatchActiveWindow(pollMs: pollMs);
